apiVersion: kritis.grafeas.io/v1beta1
kind: VulnzSigningPolicy
metadata:
  name: my-vsp
spec:
  imageVulnerabilityRequirements:
    maximumFixableSeverity: HIGH
    maximumUnfixableSeverity: HIGH
    allowlistCVEs:
      - projects/goog-vulnz/notes/CVE-2021-20305
      - projects/goog-vulnz/notes/CVE-2020-10543
      - projects/goog-vulnz/notes/CVE-2020-10878
      - projects/goog-vulnz/notes/CVE-2020-14155
      - projects/goog-vulnz/notes/CVE-2019-25013
      - projects/goog-vulnz/notes/CVE-2021-33574
      - projects/goog-vulnz/notes/CVE-2021-3520
