apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.name }}
  labels:
    app: {{ .Values.serviceName }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ .Values.kritisInstallLabel }}: ""
type: Opaque
data:
  ca.crt: {{ .Values.certificates.ca | b64enc }}
  client.crt : {{ .Values.certificates.cert | b64enc }}
  client.key: {{ .Values.certificates.key | b64enc }}
