/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImageSecurityPolicies implements ImageSecurityPolicyInterface
type FakeImageSecurityPolicies struct {
	Fake *FakeKritisV1beta1
	ns   string
}

var imagesecuritypoliciesResource = schema.GroupVersionResource{Group: "kritis", Version: "v1beta1", Resource: "imagesecuritypolicies"}

var imagesecuritypoliciesKind = schema.GroupVersionKind{Group: "kritis", Version: "v1beta1", Kind: "ImageSecurityPolicy"}

// Get takes name of the imageSecurityPolicy, and returns the corresponding imageSecurityPolicy object, and an error if there is any.
func (c *FakeImageSecurityPolicies) Get(name string, options v1.GetOptions) (result *v1beta1.ImageSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagesecuritypoliciesResource, c.ns, name), &v1beta1.ImageSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImageSecurityPolicy), err
}

// List takes label and field selectors, and returns the list of ImageSecurityPolicies that match those selectors.
func (c *FakeImageSecurityPolicies) List(opts v1.ListOptions) (result *v1beta1.ImageSecurityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagesecuritypoliciesResource, imagesecuritypoliciesKind, c.ns, opts), &v1beta1.ImageSecurityPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ImageSecurityPolicyList{}
	for _, item := range obj.(*v1beta1.ImageSecurityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageSecurityPolicies.
func (c *FakeImageSecurityPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagesecuritypoliciesResource, c.ns, opts))

}

// Create takes the representation of a imageSecurityPolicy and creates it.  Returns the server's representation of the imageSecurityPolicy, and an error, if there is any.
func (c *FakeImageSecurityPolicies) Create(imageSecurityPolicy *v1beta1.ImageSecurityPolicy) (result *v1beta1.ImageSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagesecuritypoliciesResource, c.ns, imageSecurityPolicy), &v1beta1.ImageSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImageSecurityPolicy), err
}

// Update takes the representation of a imageSecurityPolicy and updates it. Returns the server's representation of the imageSecurityPolicy, and an error, if there is any.
func (c *FakeImageSecurityPolicies) Update(imageSecurityPolicy *v1beta1.ImageSecurityPolicy) (result *v1beta1.ImageSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagesecuritypoliciesResource, c.ns, imageSecurityPolicy), &v1beta1.ImageSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImageSecurityPolicy), err
}

// Delete takes name of the imageSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeImageSecurityPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(imagesecuritypoliciesResource, c.ns, name), &v1beta1.ImageSecurityPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageSecurityPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagesecuritypoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ImageSecurityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched imageSecurityPolicy.
func (c *FakeImageSecurityPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ImageSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagesecuritypoliciesResource, c.ns, name, data, subresources...), &v1beta1.ImageSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ImageSecurityPolicy), err
}
