/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBuildPolicies implements BuildPolicyInterface
type FakeBuildPolicies struct {
	Fake *FakeKritisV1beta1
	ns   string
}

var buildpoliciesResource = schema.GroupVersionResource{Group: "kritis", Version: "v1beta1", Resource: "buildpolicies"}

var buildpoliciesKind = schema.GroupVersionKind{Group: "kritis", Version: "v1beta1", Kind: "BuildPolicy"}

// Get takes name of the buildPolicy, and returns the corresponding buildPolicy object, and an error if there is any.
func (c *FakeBuildPolicies) Get(name string, options v1.GetOptions) (result *v1beta1.BuildPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(buildpoliciesResource, c.ns, name), &v1beta1.BuildPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BuildPolicy), err
}

// List takes label and field selectors, and returns the list of BuildPolicies that match those selectors.
func (c *FakeBuildPolicies) List(opts v1.ListOptions) (result *v1beta1.BuildPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(buildpoliciesResource, buildpoliciesKind, c.ns, opts), &v1beta1.BuildPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BuildPolicyList{}
	for _, item := range obj.(*v1beta1.BuildPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested buildPolicies.
func (c *FakeBuildPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(buildpoliciesResource, c.ns, opts))

}

// Create takes the representation of a buildPolicy and creates it.  Returns the server's representation of the buildPolicy, and an error, if there is any.
func (c *FakeBuildPolicies) Create(buildPolicy *v1beta1.BuildPolicy) (result *v1beta1.BuildPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(buildpoliciesResource, c.ns, buildPolicy), &v1beta1.BuildPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BuildPolicy), err
}

// Update takes the representation of a buildPolicy and updates it. Returns the server's representation of the buildPolicy, and an error, if there is any.
func (c *FakeBuildPolicies) Update(buildPolicy *v1beta1.BuildPolicy) (result *v1beta1.BuildPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(buildpoliciesResource, c.ns, buildPolicy), &v1beta1.BuildPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BuildPolicy), err
}

// Delete takes name of the buildPolicy and deletes it. Returns an error if one occurs.
func (c *FakeBuildPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(buildpoliciesResource, c.ns, name), &v1beta1.BuildPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBuildPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(buildpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.BuildPolicyList{})
	return err
}

// Patch applies the patch and returns the patched buildPolicy.
func (c *FakeBuildPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BuildPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(buildpoliciesResource, c.ns, name, data, subresources...), &v1beta1.BuildPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BuildPolicy), err
}
