/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKritisConfigs implements KritisConfigInterface
type FakeKritisConfigs struct {
	Fake *FakeKritisV1beta1
}

var kritisconfigsResource = schema.GroupVersionResource{Group: "kritis", Version: "v1beta1", Resource: "kritisconfigs"}

var kritisconfigsKind = schema.GroupVersionKind{Group: "kritis", Version: "v1beta1", Kind: "KritisConfig"}

// Get takes name of the kritisConfig, and returns the corresponding kritisConfig object, and an error if there is any.
func (c *FakeKritisConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.KritisConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kritisconfigsResource, name), &v1beta1.KritisConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KritisConfig), err
}

// List takes label and field selectors, and returns the list of KritisConfigs that match those selectors.
func (c *FakeKritisConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.KritisConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kritisconfigsResource, kritisconfigsKind, opts), &v1beta1.KritisConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.KritisConfigList{ListMeta: obj.(*v1beta1.KritisConfigList).ListMeta}
	for _, item := range obj.(*v1beta1.KritisConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kritisConfigs.
func (c *FakeKritisConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kritisconfigsResource, opts))
}

// Create takes the representation of a kritisConfig and creates it.  Returns the server's representation of the kritisConfig, and an error, if there is any.
func (c *FakeKritisConfigs) Create(ctx context.Context, kritisConfig *v1beta1.KritisConfig, opts v1.CreateOptions) (result *v1beta1.KritisConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kritisconfigsResource, kritisConfig), &v1beta1.KritisConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KritisConfig), err
}

// Update takes the representation of a kritisConfig and updates it. Returns the server's representation of the kritisConfig, and an error, if there is any.
func (c *FakeKritisConfigs) Update(ctx context.Context, kritisConfig *v1beta1.KritisConfig, opts v1.UpdateOptions) (result *v1beta1.KritisConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kritisconfigsResource, kritisConfig), &v1beta1.KritisConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KritisConfig), err
}

// Delete takes name of the kritisConfig and deletes it. Returns an error if one occurs.
func (c *FakeKritisConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kritisconfigsResource, name), &v1beta1.KritisConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKritisConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kritisconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.KritisConfigList{})
	return err
}

// Patch applies the patch and returns the patched kritisConfig.
func (c *FakeKritisConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KritisConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kritisconfigsResource, name, pt, data, subresources...), &v1beta1.KritisConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KritisConfig), err
}
