/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cryptolib

import "errors"

// Signer contains methods to create a signed Attestation.
type Signer interface {
	CreateAttestation(privateKey, payload []byte, publicKeyID string, alg SigningAlgorithm, keyMode KeyMode) (*Attestation, error)
}

type signer struct{}

// CreateAttestation creates an Attestation whose signature is generated by
// signing the given payload with the private key. For PGP and PKIX, `payload`
// should be the raw payload data. For JWT, `payload` should be a serialized
// but unsigned token.
func (s *signer) CreateAttestation(privateKey, payload []byte, publicKeyID string, alg SigningAlgorithm, keyMode KeyMode) (*Attestation, error) {
	switch keyMode {
	case Pkix:
		return createPkixAttestation(privateKey, payload, publicKeyID, alg)
	case Pgp:
		return createPgpAttestation(privateKey, payload, publicKeyID, alg)
	case Jwt:
		return createJwtAttestation(privateKey, payload, publicKeyID, alg)
	default:
		return nil, errors.New("invalid key mode")
	}
}

// Unimplemented functions
func createPkixAttestation(privateKey, payload []byte, publicKeyID string, alg SigningAlgorithm) (*Attestation, error) {
	return nil, errors.New("attestation type not implemented")
}

func createPgpAttestation(privateKey, payload []byte, publicKeyID string, alg SigningAlgorithm) (*Attestation, error) {
	return nil, errors.New("attestation type not implemented")
}

func createJwtAttestation(privateKey, payload []byte, publicKeyID string, alg SigningAlgorithm) (*Attestation, error) {
	return nil, errors.New("attestation type not implemented")
}
