/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	scheme "github.com/grafeas/kritis/pkg/kritis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GenericAttestationPoliciesGetter has a method to return a GenericAttestationPolicyInterface.
// A group's client should implement this interface.
type GenericAttestationPoliciesGetter interface {
	GenericAttestationPolicies(namespace string) GenericAttestationPolicyInterface
}

// GenericAttestationPolicyInterface has methods to work with GenericAttestationPolicy resources.
type GenericAttestationPolicyInterface interface {
	Create(*v1beta1.GenericAttestationPolicy) (*v1beta1.GenericAttestationPolicy, error)
	Update(*v1beta1.GenericAttestationPolicy) (*v1beta1.GenericAttestationPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.GenericAttestationPolicy, error)
	List(opts v1.ListOptions) (*v1beta1.GenericAttestationPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.GenericAttestationPolicy, err error)
	GenericAttestationPolicyExpansion
}

// genericAttestationPolicies implements GenericAttestationPolicyInterface
type genericAttestationPolicies struct {
	client rest.Interface
	ns     string
}

// newGenericAttestationPolicies returns a GenericAttestationPolicies
func newGenericAttestationPolicies(c *KritisV1beta1Client, namespace string) *genericAttestationPolicies {
	return &genericAttestationPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the genericAttestationPolicy, and returns the corresponding genericAttestationPolicy object, and an error if there is any.
func (c *genericAttestationPolicies) Get(name string, options v1.GetOptions) (result *v1beta1.GenericAttestationPolicy, err error) {
	result = &v1beta1.GenericAttestationPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GenericAttestationPolicies that match those selectors.
func (c *genericAttestationPolicies) List(opts v1.ListOptions) (result *v1beta1.GenericAttestationPolicyList, err error) {
	result = &v1beta1.GenericAttestationPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested genericAttestationPolicies.
func (c *genericAttestationPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a genericAttestationPolicy and creates it.  Returns the server's representation of the genericAttestationPolicy, and an error, if there is any.
func (c *genericAttestationPolicies) Create(genericAttestationPolicy *v1beta1.GenericAttestationPolicy) (result *v1beta1.GenericAttestationPolicy, err error) {
	result = &v1beta1.GenericAttestationPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		Body(genericAttestationPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a genericAttestationPolicy and updates it. Returns the server's representation of the genericAttestationPolicy, and an error, if there is any.
func (c *genericAttestationPolicies) Update(genericAttestationPolicy *v1beta1.GenericAttestationPolicy) (result *v1beta1.GenericAttestationPolicy, err error) {
	result = &v1beta1.GenericAttestationPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		Name(genericAttestationPolicy.Name).
		Body(genericAttestationPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the genericAttestationPolicy and deletes it. Returns an error if one occurs.
func (c *genericAttestationPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *genericAttestationPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched genericAttestationPolicy.
func (c *genericAttestationPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.GenericAttestationPolicy, err error) {
	result = &v1beta1.GenericAttestationPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("genericattestationpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
