/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	scheme "github.com/grafeas/kritis/pkg/kritis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ImageSecurityPoliciesGetter has a method to return a ImageSecurityPolicyInterface.
// A group's client should implement this interface.
type ImageSecurityPoliciesGetter interface {
	ImageSecurityPolicies(namespace string) ImageSecurityPolicyInterface
}

// ImageSecurityPolicyInterface has methods to work with ImageSecurityPolicy resources.
type ImageSecurityPolicyInterface interface {
	Create(ctx context.Context, imageSecurityPolicy *v1beta1.ImageSecurityPolicy, opts v1.CreateOptions) (*v1beta1.ImageSecurityPolicy, error)
	Update(ctx context.Context, imageSecurityPolicy *v1beta1.ImageSecurityPolicy, opts v1.UpdateOptions) (*v1beta1.ImageSecurityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ImageSecurityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ImageSecurityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ImageSecurityPolicy, err error)
	ImageSecurityPolicyExpansion
}

// imageSecurityPolicies implements ImageSecurityPolicyInterface
type imageSecurityPolicies struct {
	client rest.Interface
	ns     string
}

// newImageSecurityPolicies returns a ImageSecurityPolicies
func newImageSecurityPolicies(c *KritisV1beta1Client, namespace string) *imageSecurityPolicies {
	return &imageSecurityPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imageSecurityPolicy, and returns the corresponding imageSecurityPolicy object, and an error if there is any.
func (c *imageSecurityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageSecurityPolicies that match those selectors.
func (c *imageSecurityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ImageSecurityPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ImageSecurityPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageSecurityPolicies.
func (c *imageSecurityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a imageSecurityPolicy and creates it.  Returns the server's representation of the imageSecurityPolicy, and an error, if there is any.
func (c *imageSecurityPolicies) Create(ctx context.Context, imageSecurityPolicy *v1beta1.ImageSecurityPolicy, opts v1.CreateOptions) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageSecurityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a imageSecurityPolicy and updates it. Returns the server's representation of the imageSecurityPolicy, and an error, if there is any.
func (c *imageSecurityPolicies) Update(ctx context.Context, imageSecurityPolicy *v1beta1.ImageSecurityPolicy, opts v1.UpdateOptions) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(imageSecurityPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageSecurityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the imageSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *imageSecurityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageSecurityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched imageSecurityPolicy.
func (c *imageSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
