/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	scheme "github.com/grafeas/kritis/pkg/kritis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ImageSecurityPoliciesGetter has a method to return a ImageSecurityPolicyInterface.
// A group's client should implement this interface.
type ImageSecurityPoliciesGetter interface {
	ImageSecurityPolicies(namespace string) ImageSecurityPolicyInterface
}

// ImageSecurityPolicyInterface has methods to work with ImageSecurityPolicy resources.
type ImageSecurityPolicyInterface interface {
	Create(*v1beta1.ImageSecurityPolicy) (*v1beta1.ImageSecurityPolicy, error)
	Update(*v1beta1.ImageSecurityPolicy) (*v1beta1.ImageSecurityPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ImageSecurityPolicy, error)
	List(opts v1.ListOptions) (*v1beta1.ImageSecurityPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ImageSecurityPolicy, err error)
	ImageSecurityPolicyExpansion
}

// imageSecurityPolicies implements ImageSecurityPolicyInterface
type imageSecurityPolicies struct {
	client rest.Interface
	ns     string
}

// newImageSecurityPolicies returns a ImageSecurityPolicies
func newImageSecurityPolicies(c *KritisV1beta1Client, namespace string) *imageSecurityPolicies {
	return &imageSecurityPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imageSecurityPolicy, and returns the corresponding imageSecurityPolicy object, and an error if there is any.
func (c *imageSecurityPolicies) Get(name string, options v1.GetOptions) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.Background()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageSecurityPolicies that match those selectors.
func (c *imageSecurityPolicies) List(opts v1.ListOptions) (result *v1beta1.ImageSecurityPolicyList, err error) {
	result = &v1beta1.ImageSecurityPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do(context.Background()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageSecurityPolicies.
func (c *imageSecurityPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch(context.Background())
}

// Create takes the representation of a imageSecurityPolicy and creates it.  Returns the server's representation of the imageSecurityPolicy, and an error, if there is any.
func (c *imageSecurityPolicies) Create(imageSecurityPolicy *v1beta1.ImageSecurityPolicy) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Body(imageSecurityPolicy).
		Do(context.Background()).
		Into(result)
	return
}

// Update takes the representation of a imageSecurityPolicy and updates it. Returns the server's representation of the imageSecurityPolicy, and an error, if there is any.
func (c *imageSecurityPolicies) Update(imageSecurityPolicy *v1beta1.ImageSecurityPolicy) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(imageSecurityPolicy.Name).
		Body(imageSecurityPolicy).
		Do(context.Background()).
		Into(result)
	return
}

// Delete takes name of the imageSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *imageSecurityPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		Name(name).
		Body(options).
		Do(context.Background()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageSecurityPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do(context.Background()).
		Error()
}

// Patch applies the patch and returns the patched imageSecurityPolicy.
func (c *imageSecurityPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ImageSecurityPolicy, err error) {
	result = &v1beta1.ImageSecurityPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagesecuritypolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.Background()).
		Into(result)
	return
}
