/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	scheme "github.com/grafeas/kritis/pkg/kritis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KritisConfigsGetter has a method to return a KritisConfigInterface.
// A group's client should implement this interface.
type KritisConfigsGetter interface {
	KritisConfigs() KritisConfigInterface
}

// KritisConfigInterface has methods to work with KritisConfig resources.
type KritisConfigInterface interface {
	Create(*v1beta1.KritisConfig) (*v1beta1.KritisConfig, error)
	Update(*v1beta1.KritisConfig) (*v1beta1.KritisConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.KritisConfig, error)
	List(opts v1.ListOptions) (*v1beta1.KritisConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.KritisConfig, err error)
	KritisConfigExpansion
}

// kritisConfigs implements KritisConfigInterface
type kritisConfigs struct {
	client rest.Interface
}

// newKritisConfigs returns a KritisConfigs
func newKritisConfigs(c *KritisV1beta1Client) *kritisConfigs {
	return &kritisConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the kritisConfig, and returns the corresponding kritisConfig object, and an error if there is any.
func (c *kritisConfigs) Get(name string, options v1.GetOptions) (result *v1beta1.KritisConfig, err error) {
	result = &v1beta1.KritisConfig{}
	err = c.client.Get().
		Resource("kritisconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KritisConfigs that match those selectors.
func (c *kritisConfigs) List(opts v1.ListOptions) (result *v1beta1.KritisConfigList, err error) {
	result = &v1beta1.KritisConfigList{}
	err = c.client.Get().
		Resource("kritisconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kritisConfigs.
func (c *kritisConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("kritisconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kritisConfig and creates it.  Returns the server's representation of the kritisConfig, and an error, if there is any.
func (c *kritisConfigs) Create(kritisConfig *v1beta1.KritisConfig) (result *v1beta1.KritisConfig, err error) {
	result = &v1beta1.KritisConfig{}
	err = c.client.Post().
		Resource("kritisconfigs").
		Body(kritisConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kritisConfig and updates it. Returns the server's representation of the kritisConfig, and an error, if there is any.
func (c *kritisConfigs) Update(kritisConfig *v1beta1.KritisConfig) (result *v1beta1.KritisConfig, err error) {
	result = &v1beta1.KritisConfig{}
	err = c.client.Put().
		Resource("kritisconfigs").
		Name(kritisConfig.Name).
		Body(kritisConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the kritisConfig and deletes it. Returns an error if one occurs.
func (c *kritisConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kritisconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kritisConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("kritisconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kritisConfig.
func (c *kritisConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.KritisConfig, err error) {
	result = &v1beta1.KritisConfig{}
	err = c.client.Patch(pt).
		Resource("kritisconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
