/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/grafeas/kritis/pkg/kritis/apis/kritis/v1beta1"
	scheme "github.com/grafeas/kritis/pkg/kritis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VulnzSigningPoliciesGetter has a method to return a VulnzSigningPolicyInterface.
// A group's client should implement this interface.
type VulnzSigningPoliciesGetter interface {
	VulnzSigningPolicies(namespace string) VulnzSigningPolicyInterface
}

// VulnzSigningPolicyInterface has methods to work with VulnzSigningPolicy resources.
type VulnzSigningPolicyInterface interface {
	Create(*v1beta1.VulnzSigningPolicy) (*v1beta1.VulnzSigningPolicy, error)
	Update(*v1beta1.VulnzSigningPolicy) (*v1beta1.VulnzSigningPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.VulnzSigningPolicy, error)
	List(opts v1.ListOptions) (*v1beta1.VulnzSigningPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.VulnzSigningPolicy, err error)
	VulnzSigningPolicyExpansion
}

// vulnzSigningPolicies implements VulnzSigningPolicyInterface
type vulnzSigningPolicies struct {
	client rest.Interface
	ns     string
}

// newVulnzSigningPolicies returns a VulnzSigningPolicies
func newVulnzSigningPolicies(c *KritisV1beta1Client, namespace string) *vulnzSigningPolicies {
	return &vulnzSigningPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vulnzSigningPolicy, and returns the corresponding vulnzSigningPolicy object, and an error if there is any.
func (c *vulnzSigningPolicies) Get(name string, options v1.GetOptions) (result *v1beta1.VulnzSigningPolicy, err error) {
	result = &v1beta1.VulnzSigningPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VulnzSigningPolicies that match those selectors.
func (c *vulnzSigningPolicies) List(opts v1.ListOptions) (result *v1beta1.VulnzSigningPolicyList, err error) {
	result = &v1beta1.VulnzSigningPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vulnzSigningPolicies.
func (c *vulnzSigningPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a vulnzSigningPolicy and creates it.  Returns the server's representation of the vulnzSigningPolicy, and an error, if there is any.
func (c *vulnzSigningPolicies) Create(vulnzSigningPolicy *v1beta1.VulnzSigningPolicy) (result *v1beta1.VulnzSigningPolicy, err error) {
	result = &v1beta1.VulnzSigningPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		Body(vulnzSigningPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vulnzSigningPolicy and updates it. Returns the server's representation of the vulnzSigningPolicy, and an error, if there is any.
func (c *vulnzSigningPolicies) Update(vulnzSigningPolicy *v1beta1.VulnzSigningPolicy) (result *v1beta1.VulnzSigningPolicy, err error) {
	result = &v1beta1.VulnzSigningPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		Name(vulnzSigningPolicy.Name).
		Body(vulnzSigningPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the vulnzSigningPolicy and deletes it. Returns an error if one occurs.
func (c *vulnzSigningPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vulnzSigningPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vulnzSigningPolicy.
func (c *vulnzSigningPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.VulnzSigningPolicy, err error) {
	result = &v1beta1.VulnzSigningPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vulnzsigningpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
